FROM openjdk:17

COPY app.jar /app.jar

ENV JAVA_OPTS="-Xms512m -Xmx1024m \
  -Dcom.sun.management.jmxremote \
  -Dcom.sun.management.jmxremote.port=9010 \
  -Dcom.sun.management.jmxremote.rmi.port=9010 \
  -Dcom.sun.management.jmxremote.local.only=false \
  -Dcom.sun.management.jmxremote.authenticate=false \
  -Dcom.sun.management.jmxremote.ssl=false \
  -Djava.rmi.server.hostname=127.0.0.1"

EXPOSE 9010

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /app.jar"]



